using System;
using System.IO;
using System.Linq;
using OfficeOpenXml;
using OfficeOpenXml.Drawing.Chart;

namespace LoadCalculator
{
    public class LoadReporter
    {
        public string GenerateReport(LoadCalculationResults results, string projectName, CalculationOptions options)
        {
            try
            {
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

                var desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                var fileName = $"LoadCalculationReport_{projectName}_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx";
                var filePath = Path.Combine(desktopPath, fileName);

                using (var package = new ExcelPackage())
                {
                    // Create worksheets
                    CreateSummarySheet(package.Workbook.Worksheets.Add("Executive Summary"), results, projectName);
                    CreateEquipmentListSheet(package.Workbook.Worksheets.Add("Equipment List"), results);
                    CreateCircuitAnalysisSheet(package.Workbook.Worksheets.Add("Circuit Analysis"), results);
                    CreatePanelScheduleSheet(package.Workbook.Worksheets.Add("Panel Schedule"), results);
                    CreateCalculationDetailsSheet(package.Workbook.Worksheets.Add("Calculation Details"), results);
                    CreateCodeReferencesSheet(package.Workbook.Worksheets.Add("Code References"), results);

                    package.SaveAs(new FileInfo(filePath));
                }

                return filePath;
            }
            catch (Exception ex)
            {
                throw new Exception($"Error generating load calculation report: {ex.Message}", ex);
            }
        }

        private void CreateSummarySheet(ExcelWorksheet sheet, LoadCalculationResults results, string projectName)
        {
            // Header
            sheet.Cells[1, 1].Value = "ELECTRICAL LOAD CALCULATION REPORT";
            sheet.Cells[1, 1].Style.Font.Size = 18;
            sheet.Cells[1, 1].Style.Font.Bold = true;
            sheet.Cells[1, 1, 1, 6].Merge = true;

            sheet.Cells[2, 1].Value = $"Project: {projectName}";
            sheet.Cells[3, 1].Value = $"Date: {DateTime.Now:MMMM dd, yyyy}";
            sheet.Cells[4, 1].Value = $"Generated by: ReviPrompt Lab Load Calculator";
            sheet.Cells[5, 1].Value = $"Code: {results.CodeReference}";

            // Connected Loads Summary
            int row = 7;
            sheet.Cells[row, 1].Value = "CONNECTED LOADS SUMMARY";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Load Type";
            sheet.Cells[row, 2].Value = "Connected Load (W)";
            sheet.Cells[row, 3].Value = "Percentage";
            sheet.Cells[row, 1, row, 3].Style.Font.Bold = true;
            row++;

            AddLoadRow(sheet, row++, "Lighting", results.ConnectedLoads.Lighting, results.ConnectedLoads.Total);
            AddLoadRow(sheet, row++, "Receptacles", results.ConnectedLoads.Receptacles, results.ConnectedLoads.Total);
            AddLoadRow(sheet, row++, "HVAC Equipment", results.ConnectedLoads.HVAC, results.ConnectedLoads.Total);
            AddLoadRow(sheet, row++, "Other Equipment", results.ConnectedLoads.Other, results.ConnectedLoads.Total);
            
            sheet.Cells[row, 1].Value = "TOTAL";
            sheet.Cells[row, 2].Value = results.ConnectedLoads.Total;
            sheet.Cells[row, 3].Value = "100.0%";
            sheet.Cells[row, 1, row, 3].Style.Font.Bold = true;
            row += 2;

            // Demand Loads Summary
            sheet.Cells[row, 1].Value = "DEMAND LOADS SUMMARY";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Load Type";
            sheet.Cells[row, 2].Value = "Demand Load (W)";
            sheet.Cells[row, 3].Value = "Demand Factor";
            sheet.Cells[row, 1, row, 3].Style.Font.Bold = true;
            row++;

            AddDemandRow(sheet, row++, "Lighting", results.DemandLoads.Lighting, results.ConnectedLoads.Lighting);
            AddDemandRow(sheet, row++, "Receptacles", results.DemandLoads.Receptacles, results.ConnectedLoads.Receptacles);
            AddDemandRow(sheet, row++, "HVAC Equipment", results.DemandLoads.HVAC, results.ConnectedLoads.HVAC);
            AddDemandRow(sheet, row++, "Other Equipment", results.DemandLoads.Other, results.ConnectedLoads.Other);
            
            sheet.Cells[row, 1].Value = "TOTAL DEMAND";
            sheet.Cells[row, 2].Value = results.DemandLoads.Total;
            sheet.Cells[row, 3].Value = results.ConnectedLoads.Total > 0 ? 
                $"{results.DemandLoads.Total / results.ConnectedLoads.Total:P1}" : "N/A";
            sheet.Cells[row, 1, row, 3].Style.Font.Bold = true;
            row += 2;

            // Service Requirements
            sheet.Cells[row, 1].Value = "SERVICE REQUIREMENTS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Calculated Service Load:";
            sheet.Cells[row, 2].Value = $"{results.ServiceLoad:N0} VA";
            row++;

            sheet.Cells[row, 1].Value = "System Voltage:";
            sheet.Cells[row, 2].Value = $"{results.SystemVoltage:N0}V, 3-Phase";
            row++;

            sheet.Cells[row, 1].Value = "Recommended Service Size:";
            sheet.Cells[row, 2].Value = $"{results.RecommendedServiceSize}A";
            sheet.Cells[row, 2].Style.Font.Bold = true;
            row++;

            sheet.Cells[row, 1].Value = "Load Density:";
            sheet.Cells[row, 2].Value = $"{results.LoadDensity:F1} W/sq ft";
            row += 2;

            // Notes
            sheet.Cells[row, 1].Value = "NOTES";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            row++;

            sheet.Cells[row, 1].Value = "• Calculations performed in accordance with " + results.CodeReference;
            row++;
            sheet.Cells[row, 1].Value = "• Service size includes 25% spare capacity per NEC requirements";
            row++;
            sheet.Cells[row, 1].Value = "• Load calculations based on nameplate data and design parameters";
            row++;
            sheet.Cells[row, 1].Value = "• Verify actual equipment specifications during construction";

            // Format number columns
            sheet.Cells[$"B9:B{row}"].Style.Numberformat.Format = "#,##0";

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void AddLoadRow(ExcelWorksheet sheet, int row, string loadType, double load, double total)
        {
            sheet.Cells[row, 1].Value = loadType;
            sheet.Cells[row, 2].Value = load;
            sheet.Cells[row, 3].Value = total > 0 ? $"{load / total:P1}" : "0.0%";
        }

        private void AddDemandRow(ExcelWorksheet sheet, int row, string loadType, double demandLoad, double connectedLoad)
        {
            sheet.Cells[row, 1].Value = loadType;
            sheet.Cells[row, 2].Value = demandLoad;
            sheet.Cells[row, 3].Value = connectedLoad > 0 ? $"{demandLoad / connectedLoad:P1}" : "N/A";
        }

        private void CreateEquipmentListSheet(ExcelWorksheet sheet, LoadCalculationResults results)
        {
            sheet.Cells[1, 1].Value = "EQUIPMENT LIST";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            // Headers
            var headers = new[] 
            { 
                "Element ID", "Equipment Name", "Category", "Load Type", 
                "Connected Watts", "Voltage", "Current", "Power Factor",
                "Circuit Number", "Panel Name", "Load Classification", "Location"
            };

            for (int i = 0; i < headers.Length; i++)
            {
                sheet.Cells[3, i + 1].Value = headers[i];
                sheet.Cells[3, i + 1].Style.Font.Bold = true;
            }

            // Equipment data
            int row = 4;
            foreach (var equipment in results.EquipmentLoads.OrderBy(e => e.LoadType).ThenBy(e => e.Name))
            {
                sheet.Cells[row, 1].Value = equipment.ElementId.IntegerValue;
                sheet.Cells[row, 2].Value = equipment.Name;
                sheet.Cells[row, 3].Value = equipment.Category;
                sheet.Cells[row, 4].Value = equipment.LoadType.ToString();
                sheet.Cells[row, 5].Value = equipment.ConnectedWatts;
                sheet.Cells[row, 6].Value = equipment.Voltage;
                sheet.Cells[row, 7].Value = equipment.Current;
                sheet.Cells[row, 8].Value = equipment.PowerFactor;
                sheet.Cells[row, 9].Value = equipment.CircuitNumber ?? "";
                sheet.Cells[row, 10].Value = equipment.PanelName ?? "";
                sheet.Cells[row, 11].Value = equipment.LoadClassification ?? "";
                sheet.Cells[row, 12].Value = equipment.Location ?? "";
                row++;
            }

            // Format columns
            sheet.Cells[$"E4:H{row-1}"].Style.Numberformat.Format = "#,##0.0";
            
            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateCircuitAnalysisSheet(ExcelWorksheet sheet, LoadCalculationResults results)
        {
            sheet.Cells[1, 1].Value = "CIRCUIT ANALYSIS";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            if (!results.CircuitSummary.Any())
            {
                sheet.Cells[3, 1].Value = "No circuit information available in equipment data.";
                return;
            }

            // Headers
            sheet.Cells[3, 1].Value = "Circuit Number";
            sheet.Cells[3, 2].Value = "Panel Name";
            sheet.Cells[3, 3].Value = "Total Load (W)";
            sheet.Cells[3, 4].Value = "Equipment Count";
            sheet.Cells[3, 5].Value = "Load Types";
            
            for (int i = 1; i <= 5; i++)
                sheet.Cells[3, i].Style.Font.Bold = true;

            // Circuit data
            int row = 4;
            foreach (var circuit in results.CircuitSummary)
            {
                sheet.Cells[row, 1].Value = circuit.CircuitNumber;
                sheet.Cells[row, 2].Value = circuit.PanelName;
                sheet.Cells[row, 3].Value = circuit.TotalLoad;
                sheet.Cells[row, 4].Value = circuit.EquipmentCount;
                sheet.Cells[row, 5].Value = string.Join(", ", circuit.LoadTypes.Select(lt => lt.ToString()));
                row++;
            }

            sheet.Cells[$"C4:C{row-1}"].Style.Numberformat.Format = "#,##0";
            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreatePanelScheduleSheet(ExcelWorksheet sheet, LoadCalculationResults results)
        {
            sheet.Cells[1, 1].Value = "PANEL SCHEDULE SUMMARY";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            if (!results.PanelSummary.Any())
            {
                sheet.Cells[3, 1].Value = "No panel information available in equipment data.";
                return;
            }

            // Headers
            sheet.Cells[3, 1].Value = "Panel Name";
            sheet.Cells[3, 2].Value = "Connected Load (W)";
            sheet.Cells[3, 3].Value = "Demand Load (W)";
            sheet.Cells[3, 4].Value = "Demand Factor";
            sheet.Cells[3, 5].Value = "Circuit Count";
            sheet.Cells[3, 6].Value = "Equipment Count";
            
            for (int i = 1; i <= 6; i++)
                sheet.Cells[3, i].Style.Font.Bold = true;

            // Panel data
            int row = 4;
            foreach (var panel in results.PanelSummary)
            {
                sheet.Cells[row, 1].Value = panel.PanelName;
                sheet.Cells[row, 2].Value = panel.ConnectedLoad;
                sheet.Cells[row, 3].Value = panel.DemandLoad;
                sheet.Cells[row, 4].Value = panel.ConnectedLoad > 0 ? 
                    $"{panel.DemandLoad / panel.ConnectedLoad:P1}" : "N/A";
                sheet.Cells[row, 5].Value = panel.CircuitCount;
                sheet.Cells[row, 6].Value = panel.EquipmentCount;
                row++;
            }

            sheet.Cells[$"B4:C{row-1}"].Style.Numberformat.Format = "#,##0";
            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateCalculationDetailsSheet(ExcelWorksheet sheet, LoadCalculationResults results)
        {
            sheet.Cells[1, 1].Value = "CALCULATION METHODOLOGY";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            int row = 3;

            sheet.Cells[row, 1].Value = "Code Standards Applied:";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 2].Value = results.CodeReference;
            row += 2;

            sheet.Cells[row, 1].Value = "Demand Factor Calculations:";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            row++;

            if (results.Options.UseCustomDemandFactors)
            {
                sheet.Cells[row, 1].Value = "Custom demand factors applied as specified by user.";
                row++;
                foreach (var factor in results.Options.CustomDemandFactors)
                {
                    sheet.Cells[row, 1].Value = $"• {factor.Key}: {factor.Value:P0}";
                    row++;
                }
            }
            else if (results.Options.ApplyDemandFactors)
            {
                sheet.Cells[row, 1].Value = "NEC demand factors applied per standard provisions:";
                row++;
                sheet.Cells[row, 1].Value = "• Lighting (NEC 220.42): 100% first 3000 VA, 35% remainder";
                row++;
                sheet.Cells[row, 1].Value = "• Receptacles (NEC 220.44): 100% first 10 kVA, 50% remainder";
                row++;
                sheet.Cells[row, 1].Value = "• HVAC (NEC 220.50): Building type specific factors applied";
                row++;
                sheet.Cells[row, 1].Value = "• Other Equipment: 100% unless specific provisions apply";
                row++;
            }
            else
            {
                sheet.Cells[row, 1].Value = "No demand factors applied - 100% of connected load used.";
                row++;
            }

            row += 2;
            sheet.Cells[row, 1].Value = "Service Sizing Methodology:";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            row++;
            sheet.Cells[row, 1].Value = "1. Calculate total demand load from all equipment";
            row++;
            sheet.Cells[row, 1].Value = "2. Convert to current: I = P / (V × √3 × PF)";
            row++;
            sheet.Cells[row, 1].Value = "3. Apply 25% spare capacity factor";
            row++;
            sheet.Cells[row, 1].Value = "4. Round up to next standard service size";

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateCodeReferencesSheet(ExcelWorksheet sheet, LoadCalculationResults results)
        {
            sheet.Cells[1, 1].Value = "CODE REFERENCES";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            int row = 3;

            var references = new[]
            {
                ("NEC 220.40", "General Requirements", "Basic load calculation requirements and methods"),
                ("NEC 220.42", "Lighting Load", "General illumination demand factors for commercial buildings"),
                ("NEC 220.44", "Receptacle Load", "General purpose receptacle demand factors"),
                ("NEC 220.50", "HVAC Equipment", "Air conditioning and heating equipment load calculations"),
                ("NEC 220.87", "Determining Existing Loads", "Methods for calculating existing electrical loads"),
                ("NEC 230.42", "Service Size", "Minimum service conductor size requirements"),
                ("NEC 408.30", "Panelboard Protection", "Overcurrent protection requirements for panelboards")
            };

            sheet.Cells[row, 1].Value = "Code Section";
            sheet.Cells[row, 2].Value = "Title";
            sheet.Cells[row, 3].Value = "Application";
            
            for (int i = 1; i <= 3; i++)
                sheet.Cells[row, i].Style.Font.Bold = true;
            row++;

            foreach (var (section, title, application) in references)
            {
                sheet.Cells[row, 1].Value = section;
                sheet.Cells[row, 2].Value = title;
                sheet.Cells[row, 3].Value = application;
                row++;
            }

            row += 2;
            sheet.Cells[row, 1].Value = "Important Notes:";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            row++;
            sheet.Cells[row, 1].Value = "• All calculations are estimates based on available equipment data";
            row++;
            sheet.Cells[row, 1].Value = "• Verify actual nameplate data during construction";
            row++;
            sheet.Cells[row, 1].Value = "• Local codes may have additional requirements";
            row++;
            sheet.Cells[row, 1].Value = "• Have calculations reviewed by licensed electrical engineer";

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }
    }
}