using System;
using System.IO;
using System.Linq;
using OfficeOpenXml;

namespace ModelAuditor
{
    public class ModelAuditReporter
    {
        public string GenerateReport(ModelAuditResults results, string projectName)
        {
            try
            {
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

                var desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                var fileName = $"ModelAudit_{projectName}_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx";
                var filePath = Path.Combine(desktopPath, fileName);

                using (var package = new ExcelPackage())
                {
                    // Create worksheets
                    CreateExecutiveSummarySheet(package.Workbook.Worksheets.Add("Executive Summary"), results, projectName);
                    CreateDetailedFindingsSheet(package.Workbook.Worksheets.Add("Detailed Findings"), results);
                    CreateCategoryBreakdownSheet(package.Workbook.Worksheets.Add("Category Breakdown"), results);
                    CreateActionPlanSheet(package.Workbook.Worksheets.Add("Action Plan"), results);

                    package.SaveAs(new FileInfo(filePath));
                }

                return filePath;
            }
            catch (Exception ex)
            {
                throw new Exception($"Error generating audit report: {ex.Message}", ex);
            }
        }

        private void CreateExecutiveSummarySheet(ExcelWorksheet sheet, ModelAuditResults results, string projectName)
        {
            // Header
            sheet.Cells[1, 1].Value = "MODEL HEALTH AUDIT REPORT";
            sheet.Cells[1, 1].Style.Font.Size = 18;
            sheet.Cells[1, 1].Style.Font.Bold = true;
            sheet.Cells[1, 1, 1, 6].Merge = true;

            sheet.Cells[2, 1].Value = $"Project: {projectName}";
            sheet.Cells[3, 1].Value = $"Audit Date: {results.AuditDate:MMMM dd, yyyy HH:mm}";
            sheet.Cells[4, 1].Value = $"Generated by: ReviPrompt Lab Model Auditor";

            int row = 6;

            // Health Score
            sheet.Cells[row, 1].Value = "OVERALL HEALTH SCORE";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Health Score:";
            sheet.Cells[row, 2].Value = $"{results.HealthScore:F1}/100";
            sheet.Cells[row, 2].Style.Font.Bold = true;
            sheet.Cells[row, 2].Style.Font.Size = 16;

            if (results.HealthScore >= 90)
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Green);
            else if (results.HealthScore >= 70)
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
            else
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);

            row += 2;

            // Issue summary
            sheet.Cells[row, 1].Value = "ISSUES SUMMARY";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var criticalCount = results.AllIssues.Count(i => i.Severity == AuditSeverity.Critical);
            var highCount = results.AllIssues.Count(i => i.Severity == AuditSeverity.High);
            var mediumCount = results.AllIssues.Count(i => i.Severity == AuditSeverity.Medium);
            var lowCount = results.AllIssues.Count(i => i.Severity == AuditSeverity.Low);

            sheet.Cells[row, 1].Value = "Total Issues Found:";
            sheet.Cells[row, 2].Value = results.AllIssues.Count;
            row++;

            if (criticalCount > 0)
            {
                sheet.Cells[row, 1].Value = "Critical Issues:";
                sheet.Cells[row, 2].Value = criticalCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row++;
            }

            if (highCount > 0)
            {
                sheet.Cells[row, 1].Value = "High Priority:";
                sheet.Cells[row, 2].Value = highCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                row++;
            }

            if (mediumCount > 0)
            {
                sheet.Cells[row, 1].Value = "Medium Priority:";
                sheet.Cells[row, 2].Value = mediumCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Goldenrod);
                row++;
            }

            if (lowCount > 0)
            {
                sheet.Cells[row, 1].Value = "Low Priority:";
                sheet.Cells[row, 2].Value = lowCount;
                row++;
            }

            row += 2;

            // Categories audited
            sheet.Cells[row, 1].Value = "AUDIT SCOPE";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            foreach (var category in results.CategoryResults)
            {
                sheet.Cells[row, 1].Value = $"• {category.Category}";
                sheet.Cells[row, 2].Value = $"{category.Issues.Count} issues";
                row++;
            }

            row += 2;

            // Auto-fix results
            if (results.FixResults != null)
            {
                sheet.Cells[row, 1].Value = "AUTO-FIX RESULTS";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                row += 2;

                sheet.Cells[row, 1].Value = "Issues Fixed:";
                sheet.Cells[row, 2].Value = results.FixResults.FixedCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Green);
                row++;

                sheet.Cells[row, 1].Value = "Failed to Fix:";
                sheet.Cells[row, 2].Value = results.FixResults.FailedCount;
                if (results.FixResults.FailedCount > 0)
                    sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row++;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateDetailedFindingsSheet(ExcelWorksheet sheet, ModelAuditResults results)
        {
            sheet.Cells[1, 1].Value = "DETAILED FINDINGS";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            if (!results.AllIssues.Any())
            {
                sheet.Cells[3, 1].Value = "No issues found - model passed all audit checks!";
                return;
            }

            // Headers
            var headers = new[] 
            { 
                "Severity", "Category", "Issue Type", "Description", 
                "Element IDs", "Fixable", "Recommended Action"
            };

            for (int i = 0; i < headers.Length; i++)
            {
                sheet.Cells[3, i + 1].Value = headers[i];
                sheet.Cells[3, i + 1].Style.Font.Bold = true;
            }

            // Issues data sorted by severity
            int row = 4;
            var sortedIssues = results.AllIssues
                .OrderBy(i => i.Severity)
                .ThenBy(i => i.Category)
                .ThenBy(i => i.IssueType);

            foreach (var issue in sortedIssues)
            {
                sheet.Cells[row, 1].Value = issue.Severity.ToString();
                sheet.Cells[row, 2].Value = issue.Category;
                sheet.Cells[row, 3].Value = issue.IssueType;
                sheet.Cells[row, 4].Value = issue.Description;
                sheet.Cells[row, 5].Value = string.Join(", ", issue.ElementIds.Select(id => id.IntegerValue.ToString()));
                sheet.Cells[row, 6].Value = issue.IsFixable ? "Yes" : "No";
                sheet.Cells[row, 7].Value = issue.RecommendedAction;

                // Color code by severity
                switch (issue.Severity)
                {
                    case AuditSeverity.Critical:
                        sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                        break;
                    case AuditSeverity.High:
                        sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                        break;
                    case AuditSeverity.Medium:
                        sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Goldenrod);
                        break;
                }

                row++;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateCategoryBreakdownSheet(ExcelWorksheet sheet, ModelAuditResults results)
        {
            sheet.Cells[1, 1].Value = "CATEGORY BREAKDOWN";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            int row = 3;

            foreach (var category in results.CategoryResults.OrderByDescending(c => c.Issues.Count))
            {
                // Category header
                sheet.Cells[row, 1].Value = $"{category.Category.ToUpper()}";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                row += 2;

                sheet.Cells[row, 1].Value = "Description:";
                sheet.Cells[row, 2].Value = category.Description;
                row++;

                sheet.Cells[row, 1].Value = "Summary:";
                sheet.Cells[row, 2].Value = category.Summary;
                row++;

                sheet.Cells[row, 1].Value = "Total Issues:";
                sheet.Cells[row, 2].Value = category.Issues.Count;
                row++;

                if (category.Issues.Any())
                {
                    // Issue breakdown by severity
                    var categoryCritical = category.Issues.Count(i => i.Severity == AuditSeverity.Critical);
                    var categoryHigh = category.Issues.Count(i => i.Severity == AuditSeverity.High);
                    var categoryMedium = category.Issues.Count(i => i.Severity == AuditSeverity.Medium);
                    var categoryLow = category.Issues.Count(i => i.Severity == AuditSeverity.Low);

                    if (categoryCritical > 0)
                    {
                        sheet.Cells[row, 1].Value = "Critical:";
                        sheet.Cells[row, 2].Value = categoryCritical;
                        sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                        row++;
                    }

                    if (categoryHigh > 0)
                    {
                        sheet.Cells[row, 1].Value = "High:";
                        sheet.Cells[row, 2].Value = categoryHigh;
                        sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                        row++;
                    }

                    if (categoryMedium > 0)
                    {
                        sheet.Cells[row, 1].Value = "Medium:";
                        sheet.Cells[row, 2].Value = categoryMedium;
                        sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Goldenrod);
                        row++;
                    }

                    if (categoryLow > 0)
                    {
                        sheet.Cells[row, 1].Value = "Low:";
                        sheet.Cells[row, 2].Value = categoryLow;
                        row++;
                    }
                }

                row += 2;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateActionPlanSheet(ExcelWorksheet sheet, ModelAuditResults results)
        {
            sheet.Cells[1, 1].Value = "RECOMMENDED ACTION PLAN";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            int row = 3;

            // Immediate actions for critical issues
            var criticalIssues = results.AllIssues.Where(i => i.Severity == AuditSeverity.Critical).ToList();
            if (criticalIssues.Any())
            {
                sheet.Cells[row, 1].Value = "IMMEDIATE ACTION REQUIRED";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row += 2;

                foreach (var issue in criticalIssues.Take(10)) // Top 10 critical
                {
                    sheet.Cells[row, 1].Value = $"• {issue.RecommendedAction}";
                    sheet.Cells[row, 2].Value = $"({issue.Category})";
                    row++;
                }
                row += 2;
            }

            // High priority actions
            var highIssues = results.AllIssues.Where(i => i.Severity == AuditSeverity.High).ToList();
            if (highIssues.Any())
            {
                sheet.Cells[row, 1].Value = "HIGH PRIORITY ACTIONS";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                row += 2;

                foreach (var issue in highIssues.Take(10)) // Top 10 high priority
                {
                    sheet.Cells[row, 1].Value = $"• {issue.RecommendedAction}";
                    sheet.Cells[row, 2].Value = $"({issue.Category})";
                    row++;
                }
                row += 2;
            }

            // General recommendations
            sheet.Cells[row, 1].Value = "GENERAL RECOMMENDATIONS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var recommendations = new[]
            {
                "Establish regular model audit workflow",
                "Address critical issues before project milestones",
                "Implement model standards and naming conventions",
                "Train team on proper modeling techniques",
                "Use template files with predefined standards",
                "Regular cleanup of unused families and views",
                "Coordinate with other disciplines early and often",
                "Document any intentional model exceptions"
            };

            foreach (var recommendation in recommendations)
            {
                sheet.Cells[row, 1].Value = $"• {recommendation}";
                row++;
            }

            row += 2;

            // Follow-up schedule
            sheet.Cells[row, 1].Value = "FOLLOW-UP SCHEDULE";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "• Week 1: Address all critical issues";
            row++;
            sheet.Cells[row, 1].Value = "• Week 2: Tackle high priority items";
            row++;
            sheet.Cells[row, 1].Value = "• Week 3: Work on medium priority improvements";
            row++;
            sheet.Cells[row, 1].Value = "• Week 4: Re-run audit to verify improvements";
            row++;
            sheet.Cells[row, 1].Value = "• Monthly: Schedule regular audit reviews";

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }
    }
}