using System;
using System.IO;
using System.Linq;
using OfficeOpenXml;

namespace SystemValidator
{
    public class ValidationReporter
    {
        public string GenerateReport(ValidationResults results, string projectName)
        {
            try
            {
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

                var desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                var fileName = $"MEPSystemValidation_{projectName}_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx";
                var filePath = Path.Combine(desktopPath, fileName);

                using (var package = new ExcelPackage())
                {
                    // Create worksheets
                    CreateSummarySheet(package.Workbook.Worksheets.Add("Validation Summary"), results, projectName);
                    CreateIssuesDetailSheet(package.Workbook.Worksheets.Add("Issues Detail"), results);
                    CreateSystemBreakdownSheet(package.Workbook.Worksheets.Add("System Breakdown"), results);
                    CreateRecommendationsSheet(package.Workbook.Worksheets.Add("Recommendations"), results);

                    package.SaveAs(new FileInfo(filePath));
                }

                return filePath;
            }
            catch (Exception ex)
            {
                throw new Exception($"Error generating validation report: {ex.Message}", ex);
            }
        }

        private void CreateSummarySheet(ExcelWorksheet sheet, ValidationResults results, string projectName)
        {
            // Header
            sheet.Cells[1, 1].Value = "MEP SYSTEM VALIDATION REPORT";
            sheet.Cells[1, 1].Style.Font.Size = 18;
            sheet.Cells[1, 1].Style.Font.Bold = true;
            sheet.Cells[1, 1, 1, 6].Merge = true;

            sheet.Cells[2, 1].Value = $"Project: {projectName}";
            sheet.Cells[3, 1].Value = $"Validation Date: {results.ValidationDate:MMMM dd, yyyy HH:mm}";
            sheet.Cells[4, 1].Value = $"Generated by: ReviPrompt Lab System Validator";

            // Validation scope
            int row = 6;
            sheet.Cells[row, 1].Value = "VALIDATION SCOPE";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Systems Checked:";
            sheet.Cells[row, 2].Value = string.Join(", ", results.SystemsChecked);
            row++;

            sheet.Cells[row, 1].Value = "Validation Types:";
            var validationTypes = new string[0];
            if (results.Options.CheckConnectivity) validationTypes = validationTypes.Concat(new[] { "Connectivity" }).ToArray();
            if (results.Options.CheckSystemIntegrity) validationTypes = validationTypes.Concat(new[] { "System Integrity" }).ToArray();
            if (results.Options.FindOrphanedElements) validationTypes = validationTypes.Concat(new[] { "Orphaned Elements" }).ToArray();
            sheet.Cells[row, 2].Value = string.Join(", ", validationTypes);
            row += 2;

            // Results summary
            sheet.Cells[row, 1].Value = "VALIDATION RESULTS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            // Overall status
            var criticalCount = results.Issues.Count(i => i.Severity == IssueSeverity.Critical);
            var warningCount = results.Issues.Count(i => i.Severity == IssueSeverity.Warning);
            var infoCount = results.Issues.Count(i => i.Severity == IssueSeverity.Info);

            sheet.Cells[row, 1].Value = "Overall Status:";
            var status = criticalCount > 0 ? "CRITICAL ISSUES FOUND" : 
                        warningCount > 0 ? "WARNINGS FOUND" : "SYSTEMS VALIDATED";
            sheet.Cells[row, 2].Value = status;
            sheet.Cells[row, 2].Style.Font.Bold = true;
            
            if (criticalCount > 0)
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);
            else if (warningCount > 0)
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
            else
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Green);
            
            row++;

            sheet.Cells[row, 1].Value = "Total Issues Found:";
            sheet.Cells[row, 2].Value = results.Issues.Count;
            row++;

            if (criticalCount > 0)
            {
                sheet.Cells[row, 1].Value = "Critical Issues:";
                sheet.Cells[row, 2].Value = criticalCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row++;
            }

            if (warningCount > 0)
            {
                sheet.Cells[row, 1].Value = "Warnings:";
                sheet.Cells[row, 2].Value = warningCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                row++;
            }

            if (infoCount > 0)
            {
                sheet.Cells[row, 1].Value = "Information:";
                sheet.Cells[row, 2].Value = infoCount;
                row++;
            }

            row += 2;

            // Issue breakdown by type
            sheet.Cells[row, 1].Value = "ISSUES BY TYPE";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var issuesByType = results.Issues
                .GroupBy(i => i.IssueType)
                .OrderByDescending(g => g.Count())
                .ToList();

            sheet.Cells[row, 1].Value = "Issue Type";
            sheet.Cells[row, 2].Value = "Count";
            sheet.Cells[row, 3].Value = "System";
            sheet.Cells[row, 1, row, 3].Style.Font.Bold = true;
            row++;

            foreach (var issueGroup in issuesByType)
            {
                sheet.Cells[row, 1].Value = issueGroup.Key;
                sheet.Cells[row, 2].Value = issueGroup.Count();
                sheet.Cells[row, 3].Value = issueGroup.First().SystemType;
                row++;
            }

            row += 2;

            // Recommendations
            sheet.Cells[row, 1].Value = "KEY RECOMMENDATIONS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            if (criticalCount > 0)
            {
                sheet.Cells[row, 1].Value = "• Address critical issues immediately to ensure system functionality";
                row++;
            }

            if (warningCount > 0)
            {
                sheet.Cells[row, 1].Value = "• Review warnings to prevent potential coordination issues";
                row++;
            }

            sheet.Cells[row, 1].Value = "• Verify all system connections are properly coordinated";
            row++;
            sheet.Cells[row, 1].Value = "• Review detailed issues list for specific element locations";

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateIssuesDetailSheet(ExcelWorksheet sheet, ValidationResults results)
        {
            sheet.Cells[1, 1].Value = "DETAILED ISSUES LIST";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            if (!results.Issues.Any())
            {
                sheet.Cells[3, 1].Value = "No issues found - all MEP systems validated successfully!";
                return;
            }

            // Headers
            var headers = new[] 
            { 
                "Severity", "System Type", "Issue Type", "Description", 
                "Element ID", "Location", "Recommended Action"
            };

            for (int i = 0; i < headers.Length; i++)
            {
                sheet.Cells[3, i + 1].Value = headers[i];
                sheet.Cells[3, i + 1].Style.Font.Bold = true;
            }

            // Issues data sorted by severity
            int row = 4;
            var sortedIssues = results.Issues
                .OrderBy(i => i.Severity)
                .ThenBy(i => i.SystemType)
                .ThenBy(i => i.IssueType);

            foreach (var issue in sortedIssues)
            {
                sheet.Cells[row, 1].Value = issue.Severity.ToString();
                sheet.Cells[row, 2].Value = issue.SystemType;
                sheet.Cells[row, 3].Value = issue.IssueType;
                sheet.Cells[row, 4].Value = issue.Description;
                sheet.Cells[row, 5].Value = issue.ElementId?.IntegerValue.ToString() ?? "";
                sheet.Cells[row, 6].Value = issue.Location ?? "";
                sheet.Cells[row, 7].Value = issue.RecommendedAction;

                // Color code by severity
                switch (issue.Severity)
                {
                    case IssueSeverity.Critical:
                        sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                        break;
                    case IssueSeverity.Warning:
                        sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                        break;
                }

                row++;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateSystemBreakdownSheet(ExcelWorksheet sheet, ValidationResults results)
        {
            sheet.Cells[1, 1].Value = "SYSTEM BREAKDOWN";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            // Group issues by system type
            var systemGroups = results.Issues
                .GroupBy(i => i.SystemType)
                .OrderBy(g => g.Key)
                .ToList();

            if (!systemGroups.Any())
            {
                sheet.Cells[3, 1].Value = "No issues found in any MEP systems.";
                return;
            }

            int row = 3;

            foreach (var systemGroup in systemGroups)
            {
                // System header
                sheet.Cells[row, 1].Value = $"{systemGroup.Key.ToUpper()} SYSTEM";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                row += 2;

                // System summary
                var systemCritical = systemGroup.Count(i => i.Severity == IssueSeverity.Critical);
                var systemWarnings = systemGroup.Count(i => i.Severity == IssueSeverity.Warning);
                var systemInfo = systemGroup.Count(i => i.Severity == IssueSeverity.Info);

                sheet.Cells[row, 1].Value = "Issues Summary:";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                row++;

                if (systemCritical > 0)
                {
                    sheet.Cells[row, 1].Value = $"Critical: {systemCritical}";
                    sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                    row++;
                }

                if (systemWarnings > 0)
                {
                    sheet.Cells[row, 1].Value = $"Warnings: {systemWarnings}";
                    sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                    row++;
                }

                if (systemInfo > 0)
                {
                    sheet.Cells[row, 1].Value = $"Information: {systemInfo}";
                    row++;
                }

                row++;

                // Issue types for this system
                var issueTypes = systemGroup
                    .GroupBy(i => i.IssueType)
                    .OrderByDescending(g => g.Count())
                    .ToList();

                sheet.Cells[row, 1].Value = "Issue Types:";
                sheet.Cells[row, 2].Value = "Count";
                sheet.Cells[row, 1, row, 2].Style.Font.Bold = true;
                row++;

                foreach (var issueType in issueTypes)
                {
                    sheet.Cells[row, 1].Value = issueType.Key;
                    sheet.Cells[row, 2].Value = issueType.Count();
                    row++;
                }

                row += 2;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateRecommendationsSheet(ExcelWorksheet sheet, ValidationResults results)
        {
            sheet.Cells[1, 1].Value = "VALIDATION RECOMMENDATIONS";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            int row = 3;

            sheet.Cells[row, 1].Value = "IMMEDIATE ACTION ITEMS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var criticalIssues = results.Issues.Where(i => i.Severity == IssueSeverity.Critical).ToList();
            if (criticalIssues.Any())
            {
                sheet.Cells[row, 1].Value = "Critical Issues (Address Immediately):";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row++;

                foreach (var issue in criticalIssues.Take(10)) // Top 10 critical
                {
                    sheet.Cells[row, 1].Value = $"• {issue.RecommendedAction}";
                    row++;
                }
                row++;
            }

            // General recommendations
            sheet.Cells[row, 1].Value = "GENERAL RECOMMENDATIONS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var recommendations = new[]
            {
                "Establish regular MEP system validation workflow",
                "Coordinate MEP systems early in design process",
                "Use consistent naming conventions for all MEP elements",
                "Verify all equipment connections before finalizing design",
                "Maintain clean, organized MEP system structure",
                "Document any intentionally unconnected elements",
                "Regular model audits prevent coordination issues",
                "Train team on proper MEP modeling techniques"
            };

            foreach (var recommendation in recommendations)
            {
                sheet.Cells[row, 1].Value = $"• {recommendation}";
                row++;
            }

            row += 2;

            // Follow-up actions
            sheet.Cells[row, 1].Value = "FOLLOW-UP ACTIONS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "• Re-run validation after addressing critical issues";
            row++;
            sheet.Cells[row, 1].Value = "• Coordinate with MEP consultants on unresolved issues";
            row++;
            sheet.Cells[row, 1].Value = "• Update project standards based on validation findings";
            row++;
            sheet.Cells[row, 1].Value = "• Schedule regular validation checks throughout project";

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }
    }
}