using System;
using System.IO;
using System.Linq;
using OfficeOpenXml;

namespace ElementCounter
{
    public class ElementCountReporter
    {
        public string GenerateReport(ElementCountResults results, string projectName)
        {
            try
            {
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

                var desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                var fileName = $"ElementCount_{projectName}_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx";
                var filePath = Path.Combine(desktopPath, fileName);

                using (var package = new ExcelPackage())
                {
                    // Create worksheets
                    CreateSummarySheet(package.Workbook.Worksheets.Add("Count Summary"), results, projectName);
                    CreateCategorySheet(package.Workbook.Worksheets.Add("By Category"), results);
                    
                    if (results.LevelCounts?.Any() == true)
                        CreateLevelSheet(package.Workbook.Worksheets.Add("By Level"), results);
                    
                    if (results.WorksetCounts?.Any() == true)
                        CreateWorksetSheet(package.Workbook.Worksheets.Add("By Workset"), results);
                    
                    if (results.TypeCounts?.Any() == true)
                        CreateTypeSheet(package.Workbook.Worksheets.Add("By Type"), results);
                    
                    if (results.Analysis != null)
                        CreateAnalysisSheet(package.Workbook.Worksheets.Add("Analysis"), results);

                    package.SaveAs(new FileInfo(filePath));
                }

                return filePath;
            }
            catch (Exception ex)
            {
                throw new Exception($"Error generating element count report: {ex.Message}", ex);
            }
        }

        private void CreateSummarySheet(ExcelWorksheet sheet, ElementCountResults results, string projectName)
        {
            // Header
            sheet.Cells[1, 1].Value = "ELEMENT COUNT SUMMARY";
            sheet.Cells[1, 1].Style.Font.Size = 18;
            sheet.Cells[1, 1].Style.Font.Bold = true;
            sheet.Cells[1, 1, 1, 6].Merge = true;

            sheet.Cells[2, 1].Value = $"Project: {projectName}";
            sheet.Cells[3, 1].Value = $"Count Date: {results.CountDate:MMMM dd, yyyy HH:mm}";
            sheet.Cells[4, 1].Value = $"Generated by: ReviPrompt Lab Element Counter";

            int row = 6;

            // Overall statistics
            sheet.Cells[row, 1].Value = "OVERALL STATISTICS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var totalElements = results.CategoryCounts.Values.Sum();
            sheet.Cells[row, 1].Value = "Total Elements:";
            sheet.Cells[row, 2].Value = totalElements;
            sheet.Cells[row, 2].Style.Font.Bold = true;
            sheet.Cells[row, 2].Style.Font.Size = 12;
            row++;

            sheet.Cells[row, 1].Value = "Total Categories:";
            sheet.Cells[row, 2].Value = results.CategoryCounts.Count;
            row++;

            if (results.LevelCounts?.Any() == true)
            {
                sheet.Cells[row, 1].Value = "Levels in Model:";
                sheet.Cells[row, 2].Value = results.LevelCounts.Count;
                row++;
            }

            if (results.WorksetCounts?.Any() == true)
            {
                sheet.Cells[row, 1].Value = "Worksets in Model:";
                sheet.Cells[row, 2].Value = results.WorksetCounts.Count;
                row++;
            }

            row += 2;

            // Top 10 categories
            sheet.Cells[row, 1].Value = "TOP ELEMENT CATEGORIES";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Category";
            sheet.Cells[row, 2].Value = "Count";
            sheet.Cells[row, 3].Value = "% of Total";
            sheet.Cells[row, 1, row, 3].Style.Font.Bold = true;
            row++;

            var topCategories = results.CategoryCounts.Take(10).ToList();
            foreach (var category in topCategories)
            {
                sheet.Cells[row, 1].Value = category.Key;
                sheet.Cells[row, 2].Value = category.Value;
                sheet.Cells[row, 3].Value = $"{(double)category.Value / totalElements * 100:F1}%";
                row++;
            }

            row += 2;

            // Counting options used
            sheet.Cells[row, 1].Value = "COUNTING OPTIONS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Model Elements Only:";
            sheet.Cells[row, 2].Value = results.Options.CountOnlyModelElements ? "Yes" : "No";
            row++;

            sheet.Cells[row, 1].Value = "Active View Only:";
            sheet.Cells[row, 2].Value = results.Options.CountInActiveViewOnly ? "Yes" : "No";
            row++;

            sheet.Cells[row, 1].Value = "Include Analysis:";
            sheet.Cells[row, 2].Value = results.Options.IncludeAnalysis ? "Yes" : "No";
            row++;

            sheet.Cells[row, 1].Value = "Exclude Annotations:";
            sheet.Cells[row, 2].Value = results.Options.ExcludeAnnotations ? "Yes" : "No";

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateCategorySheet(ExcelWorksheet sheet, ElementCountResults results)
        {
            sheet.Cells[1, 1].Value = "ELEMENT COUNT BY CATEGORY";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            // Headers
            sheet.Cells[3, 1].Value = "Category";
            sheet.Cells[3, 2].Value = "Count";
            sheet.Cells[3, 3].Value = "% of Total";
            sheet.Cells[3, 1, 3, 3].Style.Font.Bold = true;

            var totalElements = results.CategoryCounts.Values.Sum();
            int row = 4;

            foreach (var category in results.CategoryCounts)
            {
                sheet.Cells[row, 1].Value = category.Key;
                sheet.Cells[row, 2].Value = category.Value;
                sheet.Cells[row, 3].Value = $"{(double)category.Value / totalElements * 100:F1}%";
                row++;
            }

            // Add totals row
            sheet.Cells[row + 1, 1].Value = "TOTAL";
            sheet.Cells[row + 1, 2].Value = totalElements;
            sheet.Cells[row + 1, 3].Value = "100.0%";
            sheet.Cells[row + 1, 1, row + 1, 3].Style.Font.Bold = true;

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateLevelSheet(ExcelWorksheet sheet, ElementCountResults results)
        {
            sheet.Cells[1, 1].Value = "ELEMENT COUNT BY LEVEL";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            // Headers
            sheet.Cells[3, 1].Value = "Level";
            sheet.Cells[3, 2].Value = "Count";
            sheet.Cells[3, 3].Value = "% of Total";
            sheet.Cells[3, 1, 3, 3].Style.Font.Bold = true;

            var totalElements = results.LevelCounts.Values.Sum();
            int row = 4;

            foreach (var level in results.LevelCounts)
            {
                sheet.Cells[row, 1].Value = level.Key;
                sheet.Cells[row, 2].Value = level.Value;
                sheet.Cells[row, 3].Value = $"{(double)level.Value / totalElements * 100:F1}%";
                row++;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateWorksetSheet(ExcelWorksheet sheet, ElementCountResults results)
        {
            sheet.Cells[1, 1].Value = "ELEMENT COUNT BY WORKSET";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            // Headers
            sheet.Cells[3, 1].Value = "Workset";
            sheet.Cells[3, 2].Value = "Count";
            sheet.Cells[3, 3].Value = "% of Total";
            sheet.Cells[3, 1, 3, 3].Style.Font.Bold = true;

            var totalElements = results.WorksetCounts.Values.Sum();
            int row = 4;

            foreach (var workset in results.WorksetCounts)
            {
                sheet.Cells[row, 1].Value = workset.Key;
                sheet.Cells[row, 2].Value = workset.Value;
                sheet.Cells[row, 3].Value = $"{(double)workset.Value / totalElements * 100:F1}%";
                row++;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateTypeSheet(ExcelWorksheet sheet, ElementCountResults results)
        {
            sheet.Cells[1, 1].Value = "ELEMENT COUNT BY TYPE";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            sheet.Cells[2, 1].Value = "Detailed breakdown of element counts by specific type within each category";
            sheet.Cells[2, 1].Style.Font.Italic = true;

            // Headers
            sheet.Cells[4, 1].Value = "Category - Type";
            sheet.Cells[4, 2].Value = "Count";
            sheet.Cells[4, 1, 4, 2].Style.Font.Bold = true;

            int row = 5;

            foreach (var type in results.TypeCounts)
            {
                sheet.Cells[row, 1].Value = type.Key;
                sheet.Cells[row, 2].Value = type.Value;
                row++;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateAnalysisSheet(ExcelWorksheet sheet, ElementCountResults results)
        {
            var analysis = results.Analysis;
            if (analysis == null) return;

            sheet.Cells[1, 1].Value = "ELEMENT ANALYSIS";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            int row = 3;

            // Area calculations
            sheet.Cells[row, 1].Value = "AREA CALCULATIONS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            if (analysis.TotalWallArea > 0)
            {
                sheet.Cells[row, 1].Value = "Total Wall Area:";
                sheet.Cells[row, 2].Value = $"{analysis.TotalWallArea:F2} sq ft";
                row++;
            }

            if (analysis.TotalFloorArea > 0)
            {
                sheet.Cells[row, 1].Value = "Total Floor Area:";
                sheet.Cells[row, 2].Value = $"{analysis.TotalFloorArea:F2} sq ft";
                row++;
            }

            if (analysis.TotalRoofArea > 0)
            {
                sheet.Cells[row, 1].Value = "Total Roof Area:";
                sheet.Cells[row, 2].Value = $"{analysis.TotalRoofArea:F2} sq ft";
                row++;
            }

            row += 2;

            // Length calculations
            sheet.Cells[row, 1].Value = "LENGTH CALCULATIONS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            if (analysis.TotalWallLength > 0)
            {
                sheet.Cells[row, 1].Value = "Total Wall Length:";
                sheet.Cells[row, 2].Value = $"{analysis.TotalWallLength:F2} ft";
                row++;
            }

            row += 2;

            // Space analysis
            sheet.Cells[row, 1].Value = "SPACE ANALYSIS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Room Count:";
            sheet.Cells[row, 2].Value = analysis.RoomCount;
            row++;

            sheet.Cells[row, 1].Value = "Space Count:";
            sheet.Cells[row, 2].Value = analysis.SpaceCount;
            row += 2;

            // Family analysis
            sheet.Cells[row, 1].Value = "FAMILY ANALYSIS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Family Instances:";
            sheet.Cells[row, 2].Value = analysis.FamilyInstanceCount;
            row++;

            sheet.Cells[row, 1].Value = "Unique Families:";
            sheet.Cells[row, 2].Value = analysis.UniqueFamilyCount;
            row++;

            if (analysis.UniqueFamilyCount > 0)
            {
                sheet.Cells[row, 1].Value = "Avg Instances per Family:";
                sheet.Cells[row, 2].Value = $"{(double)analysis.FamilyInstanceCount / analysis.UniqueFamilyCount:F1}";
                row++;
            }

            row += 2;

            // MEP analysis
            sheet.Cells[row, 1].Value = "MEP ANALYSIS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "MEP Elements:";
            sheet.Cells[row, 2].Value = analysis.MEPElementCount;
            row++;

            var totalElements = results.CategoryCounts.Values.Sum();
            if (totalElements > 0)
            {
                sheet.Cells[row, 1].Value = "MEP % of Total:";
                sheet.Cells[row, 2].Value = $"{(double)analysis.MEPElementCount / totalElements * 100:F1}%";
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }
    }
}