using System;
using System.IO;
using System.Linq;
using OfficeOpenXml;

namespace DeliverableChecker
{
    public class DeliverableReporter
    {
        public string GenerateReport(DeliverableResults results, string projectName)
        {
            try
            {
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

                var desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                var fileName = $"DeliverableCheck_{projectName}_{DateTime.Now:yyyyMMdd_HHmmss}.xlsx";
                var filePath = Path.Combine(desktopPath, fileName);

                using (var package = new ExcelPackage())
                {
                    // Create worksheets
                    CreateExecutiveSummarySheet(package.Workbook.Worksheets.Add("Executive Summary"), results, projectName);
                    CreateDetailedResultsSheet(package.Workbook.Worksheets.Add("Detailed Results"), results);
                    CreateCategoryBreakdownSheet(package.Workbook.Worksheets.Add("By Category"), results);
                    CreateActionItemsSheet(package.Workbook.Worksheets.Add("Action Items"), results);

                    package.SaveAs(new FileInfo(filePath));
                }

                return filePath;
            }
            catch (Exception ex)
            {
                throw new Exception($"Error generating deliverable report: {ex.Message}", ex);
            }
        }

        private void CreateExecutiveSummarySheet(ExcelWorksheet sheet, DeliverableResults results, string projectName)
        {
            // Header
            sheet.Cells[1, 1].Value = "PROJECT DELIVERABLE READINESS REPORT";
            sheet.Cells[1, 1].Style.Font.Size = 18;
            sheet.Cells[1, 1].Style.Font.Bold = true;
            sheet.Cells[1, 1, 1, 6].Merge = true;

            sheet.Cells[2, 1].Value = $"Project: {projectName}";
            sheet.Cells[3, 1].Value = $"Check Date: {results.CheckDate:MMMM dd, yyyy HH:mm}";
            sheet.Cells[4, 1].Value = $"Generated by: ReviPrompt Lab Deliverable Checker";

            int row = 6;

            // Overall readiness score
            sheet.Cells[row, 1].Value = "OVERALL READINESS SCORE";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            sheet.Cells[row, 1].Value = "Readiness Score:";
            sheet.Cells[row, 2].Value = $"{results.OverallScore:F1}%";
            sheet.Cells[row, 2].Style.Font.Bold = true;
            sheet.Cells[row, 2].Style.Font.Size = 16;

            // Color code the score
            if (results.OverallScore >= 90)
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Green);
            else if (results.OverallScore >= 70)
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
            else
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);

            row++;

            // Overall status
            var overallStatus = results.OverallScore >= 90 ? "READY FOR DELIVERY" :
                               results.OverallScore >= 70 ? "MINOR ISSUES TO RESOLVE" : "REQUIRES ATTENTION";

            sheet.Cells[row, 1].Value = "Status:";
            sheet.Cells[row, 2].Value = overallStatus;
            sheet.Cells[row, 2].Style.Font.Bold = true;
            row += 2;

            // Check summary
            sheet.Cells[row, 1].Value = "CHECK SUMMARY";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var passedCount = results.CheckResults.Count(c => c.Status == CheckStatus.Pass);
            var warningCount = results.CheckResults.Count(c => c.Status == CheckStatus.Warning);
            var failedCount = results.CheckResults.Count(c => c.Status == CheckStatus.Fail);

            sheet.Cells[row, 1].Value = "Total Checks:";
            sheet.Cells[row, 2].Value = results.CheckResults.Count;
            row++;

            if (passedCount > 0)
            {
                sheet.Cells[row, 1].Value = "✅ Passed:";
                sheet.Cells[row, 2].Value = passedCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Green);
                row++;
            }

            if (warningCount > 0)
            {
                sheet.Cells[row, 1].Value = "⚠️ Warnings:";
                sheet.Cells[row, 2].Value = warningCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                row++;
            }

            if (failedCount > 0)
            {
                sheet.Cells[row, 1].Value = "❌ Failed:";
                sheet.Cells[row, 2].Value = failedCount;
                sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row++;
            }

            row += 2;

            // Critical issues
            var criticalIssues = results.CheckResults
                .Where(c => c.Status == CheckStatus.Fail && c.IsCritical)
                .ToList();

            if (criticalIssues.Any())
            {
                sheet.Cells[row, 1].Value = "🚨 CRITICAL ISSUES";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row += 2;

                sheet.Cells[row, 1].Value = "The following critical issues must be resolved before delivery:";
                row++;

                foreach (var issue in criticalIssues.Take(5))
                {
                    sheet.Cells[row, 1].Value = $"• {issue.CheckName}: {issue.Details}";
                    row++;
                }
                row++;
            }

            // Categories checked
            sheet.Cells[row, 1].Value = "CATEGORIES CHECKED";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var categories = results.CheckResults.GroupBy(c => c.Category).ToList();
            foreach (var category in categories)
            {
                var categoryPassed = category.Count(c => c.Status == CheckStatus.Pass);
                var categoryTotal = category.Count();
                var categoryScore = (double)categoryPassed / categoryTotal * 100;

                sheet.Cells[row, 1].Value = $"• {category.Key}:";
                sheet.Cells[row, 2].Value = $"{categoryScore:F0}% ({categoryPassed}/{categoryTotal})";
                
                if (categoryScore >= 80)
                    sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Green);
                else if (categoryScore >= 50)
                    sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                else
                    sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);

                row++;
            }

            row += 2;

            // Next steps
            sheet.Cells[row, 1].Value = "RECOMMENDED NEXT STEPS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            if (criticalIssues.Any())
            {
                sheet.Cells[row, 1].Value = "1. Address all critical issues immediately";
                row++;
            }

            if (warningCount > 0)
            {
                sheet.Cells[row, 1].Value = $"{(criticalIssues.Any() ? "2" : "1")}. Review and resolve warnings";
                row++;
            }

            sheet.Cells[row, 1].Value = $"{(criticalIssues.Any() ? (warningCount > 0 ? "3" : "2") : (warningCount > 0 ? "2" : "1"))}. Re-run deliverable check after fixes";
            row++;
            sheet.Cells[row, 1].Value = $"{(criticalIssues.Any() ? (warningCount > 0 ? "4" : "3") : (warningCount > 0 ? "3" : "2"))}. Proceed with project delivery";

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateDetailedResultsSheet(ExcelWorksheet sheet, DeliverableResults results)
        {
            sheet.Cells[1, 1].Value = "DETAILED CHECK RESULTS";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            // Headers
            var headers = new[] 
            { 
                "Status", "Category", "Check Name", "Description", 
                "Details", "Critical", "Recommendation"
            };

            for (int i = 0; i < headers.Length; i++)
            {
                sheet.Cells[3, i + 1].Value = headers[i];
                sheet.Cells[3, i + 1].Style.Font.Bold = true;
            }

            // Results data sorted by status and criticality
            int row = 4;
            var sortedResults = results.CheckResults
                .OrderBy(c => c.Status)
                .ThenByDescending(c => c.IsCritical)
                .ThenBy(c => c.Category);

            foreach (var check in sortedResults)
            {
                sheet.Cells[row, 1].Value = GetStatusSymbol(check.Status);
                sheet.Cells[row, 2].Value = check.Category;
                sheet.Cells[row, 3].Value = check.CheckName;
                sheet.Cells[row, 4].Value = check.Description;
                sheet.Cells[row, 5].Value = check.Details;
                sheet.Cells[row, 6].Value = check.IsCritical ? "Yes" : "No";
                sheet.Cells[row, 7].Value = check.Recommendation;

                // Color code by status
                switch (check.Status)
                {
                    case CheckStatus.Pass:
                        sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Green);
                        break;
                    case CheckStatus.Warning:
                        sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                        break;
                    case CheckStatus.Fail:
                        sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                        if (check.IsCritical)
                            sheet.Cells[row, 6].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                        break;
                }

                row++;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateCategoryBreakdownSheet(ExcelWorksheet sheet, DeliverableResults results)
        {
            sheet.Cells[1, 1].Value = "CATEGORY BREAKDOWN";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            int row = 3;

            var categories = results.CheckResults.GroupBy(c => c.Category).ToList();

            foreach (var category in categories.OrderBy(c => c.Key))
            {
                // Category header
                sheet.Cells[row, 1].Value = $"{category.Key.ToUpper()}";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                row += 2;

                // Category summary
                var categoryPassed = category.Count(c => c.Status == CheckStatus.Pass);
                var categoryWarnings = category.Count(c => c.Status == CheckStatus.Warning);
                var categoryFailed = category.Count(c => c.Status == CheckStatus.Fail);
                var categoryTotal = category.Count();
                var categoryScore = (double)categoryPassed / categoryTotal * 100;

                sheet.Cells[row, 1].Value = "Category Score:";
                sheet.Cells[row, 2].Value = $"{categoryScore:F1}%";
                sheet.Cells[row, 2].Style.Font.Bold = true;

                if (categoryScore >= 80)
                    sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Green);
                else if (categoryScore >= 50)
                    sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                else
                    sheet.Cells[row, 2].Style.Font.Color.SetColor(System.Drawing.Color.Red);

                row++;

                sheet.Cells[row, 1].Value = "Results:";
                sheet.Cells[row, 2].Value = $"✅ {categoryPassed}  ⚠️ {categoryWarnings}  ❌ {categoryFailed}";
                row += 2;

                // Individual checks
                sheet.Cells[row, 1].Value = "Check Details:";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                row++;

                foreach (var check in category.OrderBy(c => c.Status))
                {
                    sheet.Cells[row, 1].Value = $"{GetStatusSymbol(check.Status)} {check.CheckName}";
                    sheet.Cells[row, 2].Value = check.Details;
                    
                    switch (check.Status)
                    {
                        case CheckStatus.Pass:
                            sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Green);
                            break;
                        case CheckStatus.Warning:
                            sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                            break;
                        case CheckStatus.Fail:
                            sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                            break;
                    }

                    row++;
                }

                row += 2;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private void CreateActionItemsSheet(ExcelWorksheet sheet, DeliverableResults results)
        {
            sheet.Cells[1, 1].Value = "ACTION ITEMS";
            sheet.Cells[1, 1].Style.Font.Size = 16;
            sheet.Cells[1, 1].Style.Font.Bold = true;

            int row = 3;

            // Critical failures first
            var criticalFailures = results.CheckResults
                .Where(c => c.Status == CheckStatus.Fail && c.IsCritical)
                .ToList();

            if (criticalFailures.Any())
            {
                sheet.Cells[row, 1].Value = "🚨 CRITICAL ACTIONS (Must Complete Before Delivery)";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row += 2;

                sheet.Cells[row, 1].Value = "Priority";
                sheet.Cells[row, 2].Value = "Action Required";
                sheet.Cells[row, 3].Value = "Details";
                sheet.Cells[row, 1, row, 3].Style.Font.Bold = true;
                row++;

                int priority = 1;
                foreach (var failure in criticalFailures)
                {
                    sheet.Cells[row, 1].Value = priority++;
                    sheet.Cells[row, 2].Value = failure.Recommendation;
                    sheet.Cells[row, 3].Value = failure.Details;
                    row++;
                }
                row += 2;
            }

            // Other failures
            var otherFailures = results.CheckResults
                .Where(c => c.Status == CheckStatus.Fail && !c.IsCritical)
                .ToList();

            if (otherFailures.Any())
            {
                sheet.Cells[row, 1].Value = "❌ HIGH PRIORITY ACTIONS";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Red);
                row += 2;

                foreach (var failure in otherFailures)
                {
                    sheet.Cells[row, 1].Value = $"• {failure.Recommendation}";
                    sheet.Cells[row, 2].Value = failure.Details;
                    row++;
                }
                row += 2;
            }

            // Warnings
            var warnings = results.CheckResults
                .Where(c => c.Status == CheckStatus.Warning)
                .ToList();

            if (warnings.Any())
            {
                sheet.Cells[row, 1].Value = "⚠️ RECOMMENDED IMPROVEMENTS";
                sheet.Cells[row, 1].Style.Font.Bold = true;
                sheet.Cells[row, 1].Style.Font.Size = 14;
                sheet.Cells[row, 1].Style.Font.Color.SetColor(System.Drawing.Color.Orange);
                row += 2;

                foreach (var warning in warnings)
                {
                    sheet.Cells[row, 1].Value = $"• {warning.Recommendation}";
                    sheet.Cells[row, 2].Value = warning.Details;
                    row++;
                }
                row += 2;
            }

            // General recommendations
            sheet.Cells[row, 1].Value = "📋 GENERAL RECOMMENDATIONS";
            sheet.Cells[row, 1].Style.Font.Bold = true;
            sheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var generalRecommendations = new[]
            {
                "Save and backup the model before making changes",
                "Test all fixes in a copy of the model first",
                "Re-run deliverable check after addressing issues",
                "Coordinate with team members on shared issues",
                "Document any intentional deviations from standards",
                "Schedule final review before project delivery"
            };

            foreach (var recommendation in generalRecommendations)
            {
                sheet.Cells[row, 1].Value = $"• {recommendation}";
                row++;
            }

            sheet.Cells[sheet.Dimension.Address].AutoFitColumns();
        }

        private string GetStatusSymbol(CheckStatus status)
        {
            switch (status)
            {
                case CheckStatus.Pass:
                    return "✅";
                case CheckStatus.Warning:
                    return "⚠️";
                case CheckStatus.Fail:
                    return "❌";
                default:
                    return "?";
            }
        }
    }
}